openapi: 3.0.3
info:
  title: Sistema fichajes - OpenAPI 3.0
  version: 0.1.0
servers:
- url: http://localhost:8080
tags:
- name: usuarios
  description: Servicios relacionados con los usuarios
- name: trabajos
  description: Operations about user
- name: fichajes
  description: Servicios relacionados con los fichajes
- name: apiKey
  description: Operations about user
paths:
  /user:
    get:
      tags:
      - usuarios
      summary: Recoge un usuario dada la ID
      operationId: userGET
      parameters:
      - name: userID
        in: query
        description: ID del usuario en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Usuario no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: Usuarios
    put:
      tags:
      - usuarios
      summary: Actualizar usuario dada su ID
      operationId: userPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: ID inválida
        "404":
          description: Usuario no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: Usuarios
    post:
      tags:
      - usuarios
      summary: Crea un usuario nuevo
      operationId: userPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Usuario no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: Usuarios
    delete:
      tags:
      - usuarios
      summary: Eliminar usuario dada su ID
      operationId: userDELETE
      parameters:
      - name: userID
        in: query
        description: ID del usuario en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
        "400":
          description: ID inválida
        "404":
          description: Usuario no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: Usuarios
  /work:
    get:
      tags:
      - trabajos
      summary: Recoge un trabajo dada la ID
      operationId: workGET
      parameters:
      - name: workID
        in: query
        description: ID del trabajo en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
        "400":
          description: Trabajo no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: Trabajos
    put:
      tags:
      - trabajos
      summary: Actualizar trabajo dada su ID
      operationId: workPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Work'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
        "400":
          description: ID inválida
        "404":
          description: Trabajo no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: Trabajos
    post:
      tags:
      - trabajos
      summary: Crea un trabajo nuevo
      operationId: workPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWork'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
        "400":
          description: Trabajo no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: Trabajos
    delete:
      tags:
      - trabajos
      summary: Eliminar trabajo dada su ID
      operationId: workDELETE
      parameters:
      - name: workID
        in: query
        description: ID del trabajo en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
        "400":
          description: ID inválida
        "404":
          description: Trabajo no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: Trabajos
  /fichajes:
    get:
      tags:
      - fichajes
      summary: Recoge un fichaje dada la ID
      operationId: fichajesGET
      parameters:
      - name: fichajeID
        in: query
        description: ID del fichaje en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fichaje'
        "400":
          description: Fichaje no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: Fichajes
    put:
      tags:
      - fichajes
      summary: Actualizar fichaje dada su ID
      operationId: fichajesPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fichaje'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fichaje'
        "400":
          description: ID inválida
        "404":
          description: Fichaje no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: Fichajes
    post:
      tags:
      - fichajes
      summary: Crea un fichaje nuevo
      operationId: fichajesPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewFichaje'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fichaje'
        "400":
          description: Fichaje no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: Fichajes
    delete:
      tags:
      - fichajes
      summary: Eliminar fichaje dada su ID
      operationId: fichajesDELETE
      parameters:
      - name: fichajeID
        in: query
        description: ID del fichaje en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
        "400":
          description: ID inválida
        "404":
          description: Fichaje no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: Fichajes
  /apiKey:
    get:
      tags:
      - apiKey
      summary: Recoge un apiKey dada la ID
      operationId: apiKeyGET
      parameters:
      - name: apiKeyID
        in: query
        description: ID del apiKey en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: ApiKey no válida
        "500":
          description: Error del servidor
      x-swagger-router-controller: ApiKey
    put:
      tags:
      - apiKey
      summary: Actualizar apiKey dada su ID
      operationId: apiKeyPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiKey'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKey'
        "400":
          description: ID inválida
        "404":
          description: ApiKey no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: ApiKey
    post:
      tags:
      - apiKey
      summary: Crea un apiKey nuevo
      operationId: apiKeyPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: ApiKey no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: ApiKey
    delete:
      tags:
      - apiKey
      summary: Eliminar apiKey dada su ID
      operationId: apiKeyDELETE
      parameters:
      - name: apiKeyID
        in: query
        description: ID del apiKey en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
        "400":
          description: ID inválida
        "404":
          description: ApiKey no encontrado
        "500":
          description: Error del servidor
      x-swagger-router-controller: ApiKey
  /getFichajes:
    get:
      tags:
      - fichajes
      summary: Recoge todos los fichajes disponibles
      operationId: getFichajesGET
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayFichajes'
        "500":
          description: Error del servidor
      x-swagger-router-controller: Fichajes
  /getUserFichajes:
    get:
      tags:
      - fichajes
      summary: Recoge todos los fichajes de un usuario
      operationId: getUserFichajesGET
      parameters:
      - name: userID
        in: query
        description: ID del usuario en cuestión
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayFichajes'
        "400":
          description: Usuario no válido
        "500":
          description: Error del servidor
      x-swagger-router-controller: Fichajes
  /getWorks:
    get:
      tags:
      - trabajos
      summary: Recoge todos los trabajos disponibles
      operationId: getWorksGET
      responses:
        "200":
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayWorks'
        "500":
          description: Error del servidor
      x-swagger-router-controller: Trabajos
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 10
        nombre:
          type: string
          example: Pablo
        usuario:
          type: string
          example: PabloABC123
        clave:
          type: string
          example: PabloABC123
      example:
        clave: PabloABC123
        usuario: PabloABC123
        id: 10
        nombre: Pablo
      xml:
        name: user
    Work:
      type: object
      properties:
        id:
          type: integer
          example: 10
        nombre:
          type: string
          example: Pablo
      example:
        id: 10
        nombre: Pablo
      xml:
        name: user
    Fichaje:
      type: object
      properties:
        id:
          type: integer
          example: 10
        FechaHoraEntrada:
          type: string
          example: "2024-02-01 00:00:01"
        FechaHoraSalida:
          type: string
          example: "2024-02-01 00:00:01"
        HorasTrabajadas:
          type: number
          example: 8
        IdTrabajo:
          type: integer
          example: 1110
        IdUsuario:
          type: integer
          example: 1001
        GeolocalizacionLatitud:
          type: number
          example: 1.2398472987
        GeolocalizacionLongitud:
          type: number
          example: 1.3948713928
      example:
        GeolocalizacionLatitud: 1.2398472987
        GeolocalizacionLongitud: 1.3948713928
        IdUsuario: 1001
        FechaHoraEntrada: "2024-02-01 00:00:01"
        id: 10
        FechaHoraSalida: "2024-02-01 00:00:01"
        IdTrabajo: 1110
        HorasTrabajadas: 8
      xml:
        name: user
    ApiKey:
      type: object
      properties:
        id:
          type: integer
          example: 10
        key:
          type: string
          example: wdajhgcvwefxesCDFEWcewfjchbfewcsaDcw
      example:
        id: 10
        key: wdajhgcvwefxesCDFEWcewfjchbfewcsaDcw
      xml:
        name: user
    NewUser:
      type: object
      properties:
        nombre:
          type: string
          example: Pablo
        usuario:
          type: string
          example: PabloABC123
        clave:
          type: string
          example: PabloABC123
      xml:
        name: user
    NewWork:
      type: object
      properties:
        nombre:
          type: string
          example: Pablo
      xml:
        name: user
    NewFichaje:
      type: object
      properties:
        FechaHoraEntrada:
          type: string
          example: "2024-02-01 00:00:01"
        FechaHoraSalida:
          type: string
          example: "2024-02-01 00:00:01"
        HorasTrabajadas:
          type: number
          example: 8
        IdTrabajo:
          type: integer
          example: 1110
        IdUsuario:
          type: integer
          example: 1001
        GeolocalizacionLatitud:
          type: number
          example: 1.2398472987
        GeolocalizacionLongitud:
          type: number
          example: 1.3948713928
      xml:
        name: user
    ArrayFichajes:
      type: array
      items:
        $ref: '#/components/schemas/Fichaje'
    ArrayUsers:
      type: array
      items:
        $ref: '#/components/schemas/User'
    ArrayWorks:
      type: array
      items:
        $ref: '#/components/schemas/Work'
